# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('cursada', models.CharField(max_length=64, verbose_name='Cursada')),
                ('grupo', models.CharField(blank=True, max_length=64, null=True, verbose_name='Grupo')),
                ('anio_calendario', models.IntegerField(verbose_name='Año calendario')),
            ],
            options={
                'verbose_name_plural': 'Secciones',
                'verbose_name': 'Sección',
            },
        ),
    ]
