# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistemaDeCalificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('primer_nombre', models.CharField(max_length=64, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=64, null=True, verbose_name='Segundo nombre')),
                ('apellido', models.CharField(max_length=64, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=64, verbose_name='dni')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
                'verbose_name': 'Alumno',
            },
        ),
        migrations.CreateModel(
            name='AlumnoMateriaPromedios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primero', models.IntegerField(default=0)),
                ('segundo', models.IntegerField(default=0)),
                ('tercero', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, max_length=512, null=True)),
                ('trimestre', models.IntegerField()),
                ('es_integrador', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Exámenes',
                'verbose_name': 'Examen',
            },
        ),
        migrations.CreateModel(
            name='ExamenAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nota', models.IntegerField(null=True, verbose_name='Nota')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Alumno', verbose_name='Alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name_plural': 'Nota de alumno',
                'verbose_name': 'Nota de alumno',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_alta', models.DateField(verbose_name='Fecha alta')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha hasta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Alumno', verbose_name='Alumno')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
                'verbose_name': 'Inscripción',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre de la institución')),
                ('inicio_de_clases', models.DateField(verbose_name='Fecha de inicio de clases')),
                ('primer_trimestre', models.DateField(verbose_name='Fecha de cierre de notas del primer trimestre')),
                ('segundo_trimestre', models.DateField(verbose_name='Fecha de cierre de notas del segundo trimestre')),
                ('tercer_trimestre', models.DateField(verbose_name='Fecha de cierre de notas del tercer trimestre')),
            ],
            options={
                'verbose_name_plural': 'Institución',
                'verbose_name': 'Institución',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Seccion', verbose_name='Sección')),
                ('usuarios', models.ManyToManyField(related_name='Responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'verbose_name': 'Materia',
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('respuesta', models.TextField(max_length='4096')),
            ],
            options={
                'verbose_name_plural': 'Preguntas_Administradores',
                'verbose_name': 'Pregunta_Administrador',
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Frecuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('respuesta', models.TextField(max_length='4096')),
            ],
            options={
                'verbose_name_plural': 'Preguntas_Frecuentes',
                'verbose_name': 'Pregunta_Frecuente',
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('respuesta', models.TextField(max_length='4096')),
            ],
            options={
                'verbose_name_plural': 'Preguntas_Profesores',
                'verbose_name': 'Pregunta_Profesor',
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Materia', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='alumnomateriapromedios',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDeCalificaciones.Materia'),
        ),
    ]
